apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobx-starter-kit
  labels:
    app: mobx-starter-kit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobx-starter-kit
  template:
    metadata:
      labels:
        app: mobx-starter-kit
    spec:
      containers:
      - name: mobx-starter-kit
        image: gcr.io/kubernetes-217215/github-taweesoft-mobx-starter-kit
        ports:
        - containerPort: 8080
      restartPolicy: Always