apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mobx-starter-kit
  name: mobx-starter-kit
  labels:
    app: mobx-starter-kit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobx-starter-kit
  template:
    metadata:
      labels:
        app: mobx-starter-kit
    spec:
      containers:
      - name: mobx-starter-kit
        image: gcr.io/kubernetes-217215/github-taweesoft-mobx-starter-kit
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mobx-starter-kit
  name: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser # Change this
        image: registry.hub.docker.com/filebrowser/filebrowser # Change this
        ports:
        - containerPort: 80 # Change this
        volumeMounts:
          - name: disk
            mountPath: /srv
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: disk